[package]
name = "raytracing_test"
version = "0.1.0"
authors = ["Ene <alexene@amazon.com>"]

[dependencies]
minifb = "0.20"
rand = "0.4.2"
rayon = "1.5"

[profile.release]
incremental = true
debug = true