name: Rust

on: [push]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: rustc --version; cargo build
      
  build_MacOS:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: export PATH="$HOME/.cargo/bin:$PATH"; cargo build
