name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: apt-add-repo
      run: sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - name: apt_get_update
      run: sudo apt-get update -y -qq
    - name: install_dependencies
      run: sudo apt-get install libsdl2-dev --fix-missing
    - name: Build
      run: rustc --version; cargo build
      
  test_on_macOS:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: brew install SDL2; curl https://sh.rustup.rs -sSf | sh -s -- -y; 
    - name: build
      run: export PATH="$HOME/.cargo/bin:$PATH"; cargo build
